os: osx
language: go
go:
  - tip

install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -service=travis-ci

after_success:
  - bash <(curl -s https://codecov.io/bash)

codecov:
  token: 206ea2de-cf83-4fc2-b4ba-fad1e6eca0d9
